/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#fbf9f6",
        "surface-dim": "#dbdad7",
        "surface-bright": "#fbf9f6",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3f0",
        "surface-container": "#efeeeb",
        "surface-container-high": "#eae8e5",
        "surface-container-highest": "#e4e2df",
        "surface-variant": "#e4e2df",
        "on-surface": "#1b1c1a",
        "on-surface-variant": "#424843",
        "inverse-surface": "#30312f",
        "inverse-on-surface": "#f2f0ed",
        "outline": "#727973",
        "outline-variant": "#c1c8c2",
        "surface-tint": "#456553",
        "primary": "#032517",
        "on-primary": "#ffffff",
        "primary-container": "#1b3b2b",
        "on-primary-container": "#83a590",
        "inverse-primary": "#abcfb8",
        "secondary": "#725b38",
        "on-secondary": "#ffffff",
        "secondary-container": "#fedeb2",
        "on-secondary-container": "#78603e",
        "tertiary": "#13230c",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#283920",
        "on-tertiary-container": "#8fa382",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#c7ebd4",
        "primary-fixed-dim": "#abcfb8",
        "on-primary-fixed": "#002113",
        "on-primary-fixed-variant": "#2d4d3c",
        "secondary-fixed": "#fedeb2",
        "secondary-fixed-dim": "#e0c298",
        "on-secondary-fixed": "#281800",
        "on-secondary-fixed-variant": "#584323",
        "tertiary-fixed": "#d4e9c4",
        "tertiary-fixed-dim": "#b8cda9",
        "on-tertiary-fixed": "#0f1f09",
        "on-tertiary-fixed-variant": "#3a4c31",
        "background": "#fbf9f6",
        "on-background": "#1b1c1a",
        // Editorial brand accents
        "brand-forest": "#1B3B2B",
        "brand-gold": "#C5A880",
        "brand-sage": "#5E7153",
        "brand-cream": "#FAF8F5",
        "brand-charcoal": "#1F2421"
      },
      fontFamily: {
        serif: ["'Playfair Display'", "Georgia", "serif"],
        sans: ["'Plus Jakarta Sans'", "system-ui", "sans-serif"],
        "display-xl": ["'Playfair Display'", "serif"],
        "headline-lg": ["'Playfair Display'", "serif"],
        "headline-md": ["'Playfair Display'", "serif"],
        "headline-sm": ["'Playfair Display'", "serif"],
        "title-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-sm": ["'Plus Jakarta Sans'", "sans-serif"]
      },
      fontSize: {
        "display-xl": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-xl-mobile": ["38px", { lineHeight: "46px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "0em", fontWeight: "500" }],
        "headline-md": ["28px", { lineHeight: "36px", fontWeight: "500" }],
        "headline-sm": ["22px", { lineHeight: "30px", fontWeight: "600" }],
        "title-md": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.1em", fontWeight: "600" }]
      },
      borderRadius: {
        "sm": "0.25rem",
        DEFAULT: "0.5rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.25rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
        "full": "9999px"
      },
      boxShadow: {
        "ambient-rest": "0 8px 24px -4px rgba(27, 59, 43, 0.05), 0 2px 6px -1px rgba(197, 168, 128, 0.08)",
        "ambient-elevated": "0 20px 40px -8px rgba(27, 59, 43, 0.10), 0 4px 12px -2px rgba(197, 168, 128, 0.12)",
        "gold-glow": "0 10px 30px -5px rgba(197, 168, 128, 0.25)"
      }
    },
  },
  plugins: [],
}